### PR TITLE
add Laravel 10 support

### PR DESCRIPTION
**Pull request by pxpm**

### CODE REVIEW

**Comment by GergoKormoczy** [comment]
could you merge this one pls?

**Comment by pxpm** [comment]
This is raw dependency support.

Please remember that generators are used to generate files using Laravel conventions. 

In Laravel 10 some stuff changed, and packages that generate files for Laravel need to adapt. 

Take for example the `$dates` property on model, that should now generate an entry inside the $casts array. Probably some return types need to be added etc. 

I just open the PR as a start of something, I don't expect that this would be final in this kind of package. 

Cheers

**Comment by Jaspur** [comment]
@JeffreyWay Merge? :)

**Comment by JeffreyWay** [comment]
I don't understand why anyone is still using this package, but okay. :)

**Comment by Jaspur** [comment]
Thanks! Why? For easily making migrations via the command line with `--schema` :P @JeffreyWay

**Pull request merged**
